name: "Gatsby Audio Metadata"
description: "Add audio metadata to gatsby frontmatter."
inputs:
  src-directory:
    description: "Folder to look for frontmatter files in."
    required: true
    default: "src"
  media-directory:
    description: "Folder to look for media files in."
    required: true
    default: "static"
  audio-file-variable:
    description: "File for audio file to look for in frontmatter."
    required: true
    default: "audio_file"
  audio-duration-variable:
    description: "Frontmatter variable to write duration to."
    required: true
    default: "audio_file_duration"
  audio-size-variable:
    description: "Frontmatter variable to write file size to."
    required: true
    default: "audio_file_size"
runs:
  using: "node12"
  main: "dist/index.js"
